export const projectsData = [
    {
        id: 1,
        img: "/project1.png",
        projectName: "name one",
        overview:
            "Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!",
        myRole: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!",
        seeLiveUrl: "https://archlinux.org",
        seeCodeUrl: "https://github.com",
        tech: ["HTML5", "CSS3"],
    },

    {
        id: 2,
        img: "/project2.png",
        projectName: "name two",
        overview:
            "Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!",
        myRole: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!",
        seeLiveUrl: "https://archlinux.org",
        seeCodeUrl: "https://github.com",
        tech: ["HTML5", "CSS3"],
    },

    {
        id: 3,
        img: "/project3.png",
        projectName: "name three",
        overview:
            "Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!Lorem 1 ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!",
        myRole: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum maiores dolor, cumque blanditiis sunt debitis dolorum iusto, rem officia voluptate cum provident sit quasi iure. Fugit, non. Architecto, excepturi a!",
        seeLiveUrl: "https://archlinux.org",
        seeCodeUrl: "https://github.com",
        tech: ["HTML5", "CSS3"],
    },
]
